sonar.projectKey=unitime-maintenance
sonar.projectName=UniTime Maintenance
sonar.projectVersion=4.9-phase1

sonar.sources=JavaSource
sonar.java.source=11
sonar.sourceEncoding=UTF-8

sonar.exclusions=3rd_party/**,Documentation/**,WebContent/**,target/**,build/**
